name: Build Android App with osg-android

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release
  ANDROID_ABI: armeabi-v7a
  ANDROID_PLATFORM: android-24

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake build-essential \
          unzip curl git libglu1-mesa

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Set Environment Vars
      run: |
        echo "ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> $GITHUB_ENV
        echo "PATH=$ANDROID_NDK_HOME:$PATH" >> $GITHUB_ENV

    - name: Clone osg-android
      run: |
        git clone https://github.com/openscenegraph/OpenSceneGraph.git $HOME/osg-android
        mkdir -p $HOME/osg-android/build
        cd $HOME/osg-android/build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${ANDROID_ABI} \
          -DANDROID_PLATFORM=${ANDROID_PLATFORM} \
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
          -G Ninja
        ninja -j4

    - name: Build your osgEarth viewer Android app
      run: |
        mkdir -p build && cd build
        cmake ../src/applications/osgearth_viewer_android \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${ANDROID_ABI} \
          -DANDROID_PLATFORM=${ANDROID_PLATFORM} \
          -DOSG_DIR=$HOME/osg-android/build \
          -DOSG_INCLUDE_DIR=$HOME/osg-android/include \
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
          -G Ninja
        ninja -j4

    - name: Upload APK or libs (optional)
      uses: actions/upload-artifact@v4
      with:
        name: android-build-artifacts
        path: build/
