name: android-ndk

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release
  ANDROID_ABI: arm64-v8a
  ANDROID_PLATFORM: android-24

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 11 (for Gradle or NDK builds if needed)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
        link-to-sdk: true

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake (NDK)
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ../src/applications/osgearth_viewer_android \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ANDROID_ABI \
          -DANDROID_PLATFORM=$ANDROID_PLATFORM

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 4

    - name: Upload APK or .so output (if any)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: android-build-artifacts
        path: |
          ${{github.workspace}}/build/**/*.so
          ${{github.workspace}}/build/**/*.apk
        retention-days: 7
